apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-app
  labels:
    app: final-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-app
  template:
    metadata:
      labels:
        app: final-app
    spec:
      containers:
        - name: final-app
          image: harishree11/harishree:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: "mongodb://localhost:27017/mydatabase"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
