apiVersion: v1
kind: Service
metadata:
  name: doctor-app-service
spec:
  selector:
    app: doctor-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort
